# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
production:
  AWS_ACCESS_KEY_ID:  'AKIAI2ULBEDC6ELKEBSQ'
  AWS_SECRET_ACCESS_KEY:  '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'
  AWS_BUCKET_NAME:  'fsclub'

  SEND_CLOUD_USER_NAME: "zion_test_riiCaN"
  SEND_CLOUD_USER_KEY: "bWMbKDYJYgfwXsvk"

  MAILGUN_SMTP_PORT:  '587'
  MAILGUN_SMTP_SERVER:  'smtp.mailgun.org'
  MAILGUN_SMTP_LOGIN: 'postmaster@haidaoxueyuan.club'
  MAILGUN_SMTP_PASSWORD:  'f157cb0dea2a34cb66f8bb4454a9ab90'

development:
  SEND_CLOUD_USER_NAME: "zion_test_riiCaN"
  SEND_CLOUD_USER_KEY: "bWMbKDYJYgfwXsvk"

  MAILGUN_SMTP_PORT:  '587'
  MAILGUN_SMTP_SERVER:  'smtp.mailgun.org'
  MAILGUN_SMTP_LOGIN: 'postmaster@haidaoxueyuan.club'
  MAILGUN_SMTP_PASSWORD:  'f157cb0dea2a34cb66f8bb4454a9ab90'
